### ISSUE TITLE
go-cfclient.(*Client).getToken FAILS with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mrdavidlaing** [cloudfoundry-community/firehose-to-syslog#19]
I'm having trouble running the latest `firehose-to-syslog` as part of https://github.com/logsearch/logsearch-for-cloudfoundry/pull/26

Specifically, when I run inside my test logsearch bosh deployment with following options:
```
./firehose-to-syslog \
  --domain=run.54.183.203.97.xip.io --skip-ssl-validation \
  --user=admin --password=XXXXXXX \
  --syslog-server=127.0.0.1:5514 \
  --debug
```
It fails with:
```
panic: runtime error: invalid memory address or nil pointer dereference
```

Full output below:
```
root@fe66eaf2-c4b1-4227-b03c-453355ae0663:/var/vcap/packages/firehose-to-syslog/bin# ./firehose-to-syslog --domain=run.54.183.203.97.xip.io --skip-ssl-validation --user=admin --password=XXXXXXX --syslog-server=127.0.0.1:5514 --debug
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4797c2]

goroutine 1 [running]:
github.com/cloudfoundry-community/go-cfclient.(*Client).getToken(0xc208054180, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/client.go:180 +0xa22
github.com/cloudfoundry-community/go-cfclient.(*Client).GetToken(0xc208054180, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/client.go:156 +0x44
github.com/cloudfoundry-community/go-cfclient.(*Client).doRequest(0xc208054180, 0xc208036500, 0x45, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/client.go:111 +0x84
github.com/cloudfoundry-community/go-cfclient.(*Client).ListApps(0xc208054180, 0x0, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/apps.go:54 +0x234
github.com/cloudfoundry-community/firehose-to-syslog/caching.GetAllApp(0x0, 0x0, 0x0)
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching.go:59 +0x8c
main.main()
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/main.go:73 +0x733

goroutine 6 [chan receive]:
main.func·001()
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/main.go:60 +0x67
created by main.main
	/var/vcap/packages/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/main.go:65 +0x6d1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by shinji62** [comment]
This happen can cfclient could not acces to the api endpoint I think your domain is 54.183.203.97.xip.io and not "run." but anyway the first offset of the  api endpoint is hardcoded  is api.
```golang   
apiEndpoint := fmt.Sprintf("https://api.%s", *domain)
uaaEndpoint := fmt.Sprintf("https://uaa.%s", *domain)
dopplerEndpoint := fmt.Sprintf("wss://doppler.%s", *domain)
```

So I guess api.54.183.203.97.xip.io don t exist neither.

**Comment by mrdavidlaing** [comment]
The domain is definately `run.`
```
curl -k https://api.run.54.183.203.97.xip.io/info
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"http://login.run.54.183.203.97.xip.io","token_endpoint":"https://uaa.run.54.183.203.97.xip.io","allow_debug":true}
curl -k https://uaa.run.54.183.203.97.xip.io/oauth/token
{"error":"unauthorized","error_description":"An Authentication object was not found in the SecurityContext"}
```

Do you know what the `curl` equivalent of the HTTP POST being made at [`go-cfclient/client.go#L161-L189`](https://github.com/cloudfoundry-community/firehose-to-syslog/blob/develop/Godeps/_workspace/src/github.com/cloudfoundry-community/go-cfclient/client.go#L161-L189) would be?

**Comment by shinji62** [comment]
Since due to certificate error on the uaa
```
2015/04/19 23:19:56 Error reading response Post https://uaa.run.54.183.203.97.xip.io/oauth/token: x509: certificate is valid for , not uaa.run.54.183.203.97.xip.io
```

**Comment by mrdavidlaing** [comment]
I'm attempting to use the `--skip-ssl-validation` flag - does that not work anymore?

**Comment by shinji62** [comment]
No because simon add the gocfcliemt lib I will make a PR to support insecure ssl validation

**Comment by mrdavidlaing** [comment]
Aha!  Ok, then that must be the root cause.

Out of interest, how are you adding a valid SSL certificate to your test environment?

Also, how did you get that error message?

**Comment by shinji62** [comment]
I added a custom CA and sign with it.
I am making a PR to the lib gocfclient

**Comment by shinji62** [comment]
Pr made, hopefully should be resolve tomorrow
https://github.com/cloudfoundry-community/go-cfclient/pull/3

**Comment by mrdavidlaing** [comment]
Great, thanks.

I have merge rights for https://github.com//cloudfoundry-community/go-cfclient; so I'll get the PR merged if the maintainers haven't done anything by tomorrow.

Thanks again for all the help!

**Comment by shinji62** [comment]
Done : https://github.com/cloudfoundry-community/firehose-to-syslog/pull/20

**Comment by shinji62** [comment]
Works 
```
{"cf_app_id":"d7d702c9-7863-4d16-a375-be7cd960022d","cf_app_name":"prodApp1","cf_org_id":"8005f45b-76d9-4038-8ca1-9e0a85ed5be0","cf_org_name":"system","cf_space_id":"5c98b860-f5d2-444c-b923-d91b277b5269","cf_space_name":"production","event_type":"LogMessage","level":"info","message_type":"OUT","msg":"prodApp1.apps.54.183.203.97.xip.io - [20/04/2015:16:29:53 +0000] \"GET / HTTP/1.1\" 200 7 \"-\" \"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)\" 10.10.2.6:43624 x_forwarded_for:\"91.109.115.41, 10.10.2.6\" vcap_request_id:41d114ef-e28e-4771-7edd-abc24a1ec343 response_time:0.001209302 app_id:d7d702c9-7863-4d16-a375-be7cd960022d\n","origin":"router__0","source_instance":"0","source_type":"RTR","time":"2015-04-20T09:29:38-07:00","timestamp":1429547393661293980}


{"cf_app_id":"d7d702c9-7863-4d16-a375-be7cd960022d","cf_app_name":"prodApp1","cf_org_id":"8005f45b-76d9-4038-8ca1-9e0a85ed5be0","cf_org_name":"system","cf_space_id":"5c98b860-f5d2-444c-b923-d91b277b5269","cf_space_name":"production","event_type":"LogMessage","level":"info","message_type":"OUT","msg":"prodApp1.apps.54.183.203.97.xip.io - [20/04/2015:16:30:53 +0000] \"GET / HTTP/1.1\" 200 7 \"-\" \"Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)\" 10.10.2.6:43751 x_forwarded_for:\"46.165.195.139, 10.10.2.6\" vcap_request_id:5cd57356-5a4b-44c3-561f-3d6282dfb41e response_time:0.001234369 app_id:d7d702c9-7863-4d16-a375-be7cd960022d\n","origin":"router__0","source_instance":"0","source_type":"RTR","time":"2015-04-20T09:30:38-07:00","timestamp":1429547453589996438}
```

**Comment by mrdavidlaing** [comment]
Great - I can confirm this works in my test environment too.

Thanks!
