### ISSUE TITLE
Ingestor_Cloudfoundry_Firehose SIGSEGV: segmentation violation /Missing logs

### ISSUE THREAD

**Issue by Scoobed** [cloudfoundry-community/firehose-to-syslog#217]
goroutine 41 [running]:
github.com/cloudfoundry-community/firehose-to-syslog/caching.(*CacheLazyFill).normaliseAndSaveEntityToDatabase(0xc000206420, 0xa2ea43, 0x4, 0xc0002b8990, 0x24, 0x0, 0x0, 0x0)
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_lazyfill.go:145 +0x90
github.com/cloudfoundry-community/firehose-to-syslog/caching.(*CacheLazyFill).getEntity(0xc000206420, 0xa2ea43, 0x4, 0xc0002b8930, 0x24, 0xc000363d80, 0xc000363d80, 0x4c8a2e)
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_lazyfill.go:121 +0x364
github.com/cloudfoundry-community/firehose-to-syslog/caching.(*CacheLazyFill).GetApp(0xc000206420, 0xc0002b8930, 0x24, 0x1, 0x1, 0xc0002b8930)
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/caching/caching_lazyfill.go:242 +0x6f
github.com/cloudfoundry-community/firehose-to-syslog/events.(*Event).AnnotateWithAppData(0xc000343020, 0xafe200, 0xc000206420)
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/events/events.go:130 +0x144
github.com/cloudfoundry-community/firehose-to-syslog/eventRouting.(*EventRoutingDefault).RouteEvent(0xc00054a910, 0xc00010ebd0)
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/eventRouting/eventrouting_default.go:68 +0x14c
github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).ReadLogsBuffer(0xc0004ec000, 0xb05fe0, 0xc00002e140)
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:119 +0x1a2
created by github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient.(*FirehoseNozzle).Start
        /var/vcap/data/compile/firehose-to-syslog/src/github.com/cloudfoundry-community/firehose-to-syslog/firehoseclient/firehoseclient.go:77 +0xb4
[2019-04-28 23:04:54.584610656 +0000 UTC m=+194614.078039854] Exception occurred! Message: Missed Logs  Details: 10000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c61c0]

**Comment by Scoobed** [comment]
This is latest release from v210.1.0 - this is being seen on a new deployment
